### ISSUE TITLE
Getting tax amount of zero on almost every call

### ISSUE THREAD

**Issue by tk5446** [drewtempelmeyer/tax_cloud#27]
Hi,
I am getting 0.0 returned for almost every call I make. The only time I have gotten a real value back is when I use the addresses in the examples. Is there something I need to do with my account to turn on real values?

Thanks, Tom

**Comment by dblock** [comment]
I think you need to understand Nexus.

The README has a paragraph about it:

_TaxCloud manages a list of states in which you can calculate sales tax. The default setup will only have SSUTA (Streamlined Sales and Use Tax Agreement) states enabled. All other states will return $0 for tax values. To enable other states, go to taxcloud.net/account/states._

There's tax only if the buyer in a state where the seller has nexus.

**Comment by tk5446** [comment]
Go it. Thank you
