### ISSUE TITLE
Not an issue, but a quick question

### ISSUE THREAD

**Issue by thomasjoyce** [drewtempelmeyer/tax_cloud#28]
How to you get the actual tax percentage base on address given? 

I see tax amount return the calculated tax but i want the actual tax percentage to be show to customer as well. thanks for creating this amazing gem :- )

**Comment by drewtempelmeyer** [comment]
Hey, @thomasjoyce!

If all of the items are taxable, you can simply calculate the percentage based on the amount returned against the total.

I'll create an issue to add support for returning the sales tax percentage.

**Comment by thomasjoyce** [comment]
thanks for responding quickly. good to know.  :-)
