### ISSUE TITLE
TaxCloud::TaxCodes::PREPARED_FOOD got tax?

### ISSUE THREAD

**Issue by thomasjoyce** [drewtempelmeyer/tax_cloud#30]
Hi,

I try calling taxCloud with  "TaxCloud::TaxCodes::PREPARED_FOOD" [ tic ] 
and i got a tax number value return back. Any idea why? 
i thought we don't tax on food purchases?

I look thru Groupon site to verify and see that they don't tax food purchase from merchant store.
Any idea what am i missing here? Thanks for your help.
US tax is so complicated and i'm trying to figure out what is taxable and what is not.  :- )

**Comment by dblock** [comment]
Welcome to the world of pain :) I don't have the answer for this but the better place to ask it is probably with https://taxcloud.net, the gem is just a wrapper and an unofficial one for that matter (aka one that works :)

**Comment by drewtempelmeyer** [comment]
@thomasjoyce it certainly depends on state, county, and city. In Texas, prepared foods are taxable. In most cases, tax is applied if the origin and destination are within the same state.

I don't really use Groupon, but I've never seen food items available. I believe what's being sold are redeemable coupons/certificates for specific food items.

**Comment by thomasjoyce** [comment]
Daniel, Drew, thanks for responding so quickly. 

yeah, i wish this was more straightforward to figure out. :- ) 
I guess i will check with the taxcloud folks. 

you are right, Drew, Groupon don't tax food coupon values, i guess it is a good things for customers.  :- )

**Comment by dblock** [comment]
I'll close this.
