### ISSUE TITLE
Does tax_cloud has the ability to trigger from client side as well? 

### ISSUE THREAD

**Issue by thomasjoyce** [drewtempelmeyer/tax_cloud#31]
Hi Drew,

 I stumble on http://dev.taxcloud.net/2013/10/03/taxcloud-js_stripe/ 
and was wondering if you know / some suggestions on what will be the best way to do the same using tax_cloud gem? 

currently all the tax calculations get trigger via ajax request to the server and from there i use the tax cloud gem to calculate the request. I was thinking maybe some request will be ideal to trigger it directly from the client side directly to TaxCloud server and not even calling our server at all. 

But i want to still use the tax cloud gem if possible for initial connection[passing the api keys]. 
Was wondering is this possible? 

I look thru the page link above and got stuck on :

```
"Act 1: The Setup".....
If you run PHP on your server, download our TaxCloud.php proxy file
If you run IIS/C#/ASP.NET, download our TaxCloud.aspx proxy file
```

trying to figure out how to pass in the initial api keys connection using tax cloud gem.
Try contacting taxcloud folks but have not getting any response yet so i figure maybe you encounter this page link before and have some clue/expertise on what direction approach will be the best for client side request only? Not familiar with their php code that is why i got stuck.  :- )

Thanks again for your help : - )

**Comment by ghepting** [comment]
If you wanted to call any method is this tax_cloud gem which is backend ruby code you would create an API in your backend ruby service to expose an interface for a javascript frontend application. This issue is irrelevant/obsolete (and very, very old). I advise closing :)
