### ISSUE TITLE
Dockerize and Support for Ruby 1.9.3

### ISSUE THREAD

**Issue by mrbiggred** [drewtempelmeyer/tax_cloud#39]
Thank you for creating this gem.  I created an example program to test the gem without mocking out TaxCloud and it works great.  

To create my example program I created a Docker container.  The only problem is the Docker container is for Ruby 1.9.3, which is the production environment I eventually need to incorporate this gem into.  The joys of supporting legacy code.  To get everything working I had to deprecate the RuboCop from 0.51.0 to 0.41.2.

The other issue is running the tests results in lots of warnings but no errors.  I tried running the tests in Ruby 2.3 and got a similar list of errors.  Is there something I'm missing or is everyone getting a bunch of warnings when running the tests?

Would you be interested in a pull request for the Docker Ruby 1.9.3 setup?  If so would you like it in a separate Ruby 1.9.3 branch?  Thanks.

**Comment by dblock** [comment]
I don't think this gem is interested in supporting Ruby 1.9.3, you shouldn't be running that! :)

**Comment by mrbiggred** [comment]
In case anyone finds this issue via Google and needs to use TaxCloud with a legacy code base please try the fork below.  Constructive feedback is much appreciated.

GitHub:
https://github.com/corgibytes/tax_cloud

Gem:
https://rubygems.org/gems/corgibytes-tax_cloud

Thank you @dblock and everyone else for creating the TaxCloud gem.  It works well and was relatively painless to back port to Ruby 1.9.3.  All the best.
